version: "3.7"

services:
  example:
    container_name: khazna
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "80:4200"
